### ISSUE TITLE
JSS article template

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/RandomisedTrialsEmulation#1]
I've added the templates for a JSS article into the vignettes folder. There are two versions, the one from JSS themselves which uses latex and sweave  (in vignettes/JSS_latex) and the "rticles" one which uses Rmarkdown and knitr (in vignettes/JSS_Rmd). 

I don't know which one will work better. Do you have a preference @lisu-stats

**Comment by lisu-stats** [comment]
JSS only requires that submission needs to follow their style guide. I only used Rmarkdown before,  so I think "rticles" would be good for me.
