### ISSUE TITLE
1 vs 0-indexing bug?

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/RandomisedTrialsEmulation#2]
I was getting a crash in this function sometimes and I think there may be a bug because we use t_period as an index for a c++ vector. I think t_period (which is "for_period" in the data.table) can start from t=1. I might have introduced the bug elsewhere in the 'chunks ' branch though...

https://github.com/CAM-Roche/RandomisedTrialsEmulation/blob/8750ce5cb7782e91bd9d799ab2dd3699a95f8331/src/code.cpp#L18-L24

**Comment by RoonakR** [comment]
> I was getting a crash in this function sometimes and I think there may be a bug because we use t_period as an index for a c++ vector. I think t_period (which is "for_period" in the data.table) can start from t=1. I might have introduced the bug elsewhere in the 'chunks ' branch though...
> 
> https://github.com/CAM-Roche/RandomisedTrialsEmulation/blob/8750ce5cb7782e91bd9d799ab2dd3699a95f8331/src/code.cpp#L18-L24

Could you please provide some examples of which you had the crashing problem?

**Comment by gravesti** [comment]
Attached is some code that gives error 

> `Error in expand_func(.SD, (maxperiod - minperiod) + 1, minperiod) : 
  index error`

The crash happens on id=2. It seems to be related to `use_censor=1`. It doesn't happen if this isn't set.

[example.csv](https://github.com/CAM-Roche/RandomisedTrialsEmulation/files/7251675/example.csv)

`data_preparation(data_path = "example.csv",
                 id = "id",
                 period = "num_period",
                 treatment = "treatment",
                 outcome = "event",
                 eligible = "ecmet",
                 model_var = "assigned_treatment",
                 use_censor = 1,
                 outcomeCov = c("var1","var2","var3"),
                 outcomeCov_var = c("var1","var2","var3"),
                 data_dir =tempdir(),
                 numCores = 1
)`

**Comment by RoonakR** [comment]
> Attached is some code that gives error
> 
> > `Error in expand_func(.SD, (maxperiod - minperiod) + 1, minperiod) :    index error`
> 
> The crash happens on id=2. It seems to be related to `use_censor=1`. It doesn't happen if this isn't set.
> 
> [example.csv](https://github.com/CAM-Roche/RandomisedTrialsEmulation/files/7251675/example.csv)
> 
> `data_preparation(data_path = "example.csv", id = "id", period = "num_period", treatment = "treatment", outcome = "event", eligible = "ecmet", model_var = "assigned_treatment", use_censor = 1, outcomeCov = c("var1","var2","var3"), outcomeCov_var = c("var1","var2","var3"), data_dir =tempdir(), numCores = 1 )`

Did you use this setting and data in SAS macro to see the results?

**Comment by gravesti** [comment]
The SAS macro can expand the data. Attached is the _SWITCH data generated with those parameters.
[example_SAS_SWITCH.csv](https://github.com/CAM-Roche/RandomisedTrialsEmulation/files/7265190/example_SAS_SWITCH.csv)

**Comment by gravesti** [comment]
Thanks! It fixes that one. I still get some errors. I will prepare another example.

**Comment by gravesti** [comment]
I tried to investigate. I think this is working...
In lr_utils.R
``` 
  switch_data[expand == 1, expand := expand_func_R(.SD, min(for_period)), by=id]
```
and a new R function
```
expand_func_R <- function(d, first_period){
  n <- nrow(d)
  ex <- rep(1, n+first_period)
  expand <- rep(1, n)
  t_period <- d$for_period
  t_new <- d$period_new
  t_switch <- d$switch_new

  for(i in seq.int(n)){
    expand[i] <- ex[t_period[i]]
    if(t_period[i] == t_new[i] && t_switch[i] == 1){
      idx = seq(first_period, t_period[i])
      ex[idx] <- 0
    }
  }
    expand
}
```

**Comment by RoonakR** [comment]
> seq(first_period, t_period[i])
>       ex[idx] <- 0

I will have a look but I didn't use R for this because for and loops are so slow in R so I used C++

**Comment by RoonakR** [comment]
> I tried to investigate. I think this is working... In lr_utils.R
> 
> ```
>   switch_data[expand == 1, expand := expand_func_R(.SD, min(for_period)), by=id]
> ```
> 
> and a new R function
> 
> ```
> expand_func_R <- function(d, first_period){
>   n <- nrow(d)
>   ex <- rep(1, n+first_period)
>   expand <- rep(1, n)
>   t_period <- d$for_period
>   t_new <- d$period_new
>   t_switch <- d$switch_new
> 
>   for(i in seq.int(n)){
>     expand[i] <- ex[t_period[i]]
>     if(t_period[i] == t_new[i] && t_switch[i] == 1){
>       idx = seq(first_period, t_period[i])
>       ex[idx] <- 0
>     }
>   }
>     expand
> }
> ```

I will have a look but I didn't use R for this because for and loops are so slow in R so I used C++
