### ISSUE TITLE
case control sampling questions

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/RandomisedTrialsEmulation#20]
Hi @lisu-stats @RoonakR 

What do you think is the best approach when for the case-control sampling when there are not enough controls for the specified ratio of case:controls in a period? Should the cases be sampled with replacement? Or just use them all and have fewer than requested?

**Comment by lisu-stats** [comment]
@gravesti I think we shall use the available controls if the nubmer of controls requrested is larger than the avaiable ones.
