### ISSUE TITLE
splines with parglm

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/RandomisedTrialsEmulation#23]
Can we use spines with parglm? ie ` y ~ ns(followup_time)`

**Comment by RoonakR** [comment]
@gravesti @lisu-stats Is it only for followup_time? do users need to say they want to use spline for it with a variable?

**Comment by lisu-stats** [comment]
We have the following option for now:

include_followup_time_case=1,
 include_expansion_time_case=1,

which will include the linear and quadratic terms of the variables.  

We could set the option value ='2' to include spline terms saved in another option, say, followup_time_spline=' ns(followup_time, df=4)' . But users could of course specify their own spline terms in 'followup_time_spline' too, following ns() options.

**Comment by lisu-stats** [comment]
> @lisu-stats @gravesti should I also add the spline function and its result as a column in the dataset?

Yes, please add the matrix of spline basis in the final dataset. Thank you.

**Comment by gravesti** [comment]
Initial support for splines has been merged.
Further ideas:

- [ ] Calculating splines for big data in separate trial files
- [ ] Splines after case-control sampling
