### ISSUE TITLE
Print output

### ISSUE THREAD

**Issue by lisu-stats** [CAM-Roche/RandomisedTrialsEmulation#40]
@RoonakR @gravesti Hi, Roonak, Isaac. Is there any way to silence the output for the model fitting on screen? My student Juliette is running bootstrap using the package and the output becomes very lengthy. So it would be good to have this option. Thanks!

**Comment by gravesti** [comment]
Yes, I will add this. In the meantime Juliette could try to use
suppressMessages() around the model fitting code to hide the outputs.

https://stat.ethz.ch/R-manual/R-devel/library/base/html/message.html
-- 

Isaac Gravestock, PhD

Data Scientist

Real World Data, PD Data Sciences

F.Hoffmann - La Roche Ltd

Tel:      (+41) 79 158 31 85

e-mail: ***@***.*** ***@***.***>

**Comment by gravesti** [comment]
@lisu-stats @juliettelimozin I've almost finished implementing this now. The functions will have an option `quiet = TRUE`.
I've also added another dependency, so you'll need to `install.packages('checkmate')`.
