### ISSUE TITLE
Limiting observation period options

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/RandomisedTrialsEmulation#63]
@lisu-stats 
For limiting the observation period there are different thing that can be done, such as

1. limit maximum follow up time in a trial
2. Only allow trials to begin in certain periods
3. Censor the whole data set at some (calendar) time 

Currently in `initiators()` we have the following arguments

- `first_period`: First period value to start expanding about
- `last_period`: Last period value to expand about
- `first_followup`: First follow-up period
- `last_followup`: Last follow-up period

Should these correspond with the above? 1 and 2? Something else?
Can we give better names and descriptions?
Need to implement tests to ensure correct and expected behaviour.

See also #43

**Comment by lisu-stats** [comment]
@gravesti 
I just tried the `first_period` and `last_period` in the `data_preparation` function. They did not limit the trial periods for expansion. The resulting data are exactly the same with/without these options. 

The ` first_followup` and `last_followup` in the `data_modelling` function worked. Basically, they will include observations between the ` first_followup` and `last_followup` for fitting the logistic models. This will fulfil the requirement if users want to limit maximum follow-up time in a trial (1st point in your list).

**Comment by lisu-stats** [comment]
The `first_period` and `last_period` options did change the summaries such as the `min_period` and `max_period` , but the expanded data don't look different.

**Comment by gravesti** [comment]
> - The user can select only part of follow-up to be included in all analyses by setting first_period= and last_period= to the desired first and last periods (inclusive).
> - The user may also limit the periods included in the outcome model by setting first_followup= and last_followup= to the desired first and last follow-up periods. Notice that periods not included in this range will still contribute to the weight models.

@lisu-stats Do you think `first_period`/`last_period` should have an impact before the weight models are calculated?
I suppose the user could easily filter the data themselves if that's what they wanted, which would be my 3.

So the I think `first_period`/`last_period`  needs to be implemented as number 2.

**Comment by lisu-stats** [comment]
@gravesti I just checked the SAS macro. It did exclude observations outside `first_period/last_period` for estimating weights and for expanding data. I agree these options should be implemented as number 2. Yes, number 3 can be done by users by filtering the original data.

**Comment by lisu-stats** [comment]
> @gravesti The SAS macro `first_period/last_period` options do not work properly either. Somehow it gives different fitted weight models when setting `first_period/last_period` or not. But in the end, the expanded data look exactly the same with/without these options.
> 
> The comments for these options state that they should specify the periods to expand the data.
> 
> > first_period = ,    /* first period to start expanding about _/
> > last_period = ,     /_ last period to expand about */

Just found that when fitting the weights models,  `first_period/last_period` options in the SAS macro will use subsetted data. But when expanding data, the SAS macro runs into errors:

```
> ERROR: Array subscript out of range at line 95 column 41.
>  t=4 A=1 X1=0 X2=-0.453560925 X3=0 X4=-0.307927217 age_s=1.8333333333 Y=0 C=0 eligible=0 _time_of_event=9999 _regime_start=2
>  _newid_=3 _cumA_=3 switch=0 _Am1_=1 _time_on_regime_=2 _time_on_regime2_=4 _started0=0 _started1=1 _stop0=0 _stop1=0 _eligible0=0
>  _eligible1=1 _eligible0_sw=0 _eligible1_sw=1 p0_d=. p0_n=. p1_d=0.4746074122 p1_n=0.6322294426 pC_d0=. pC_n0=. pC_d1=0.9841235746
>  pC_n1=0.9514925373 wt=1.2879409487 pC_n=0.9514925373 pC_d=0.9841235746 wtC=0.9668425408 FIRST._newid_=0 LAST._newid_=0 FIRST.t=1
>  LAST.t=1 for_period=. _followup_time=. _assigned_treatment=. for_period2=. _followup_time2=. _case=. X1_new=. X2_new=. X3_new=.
>  X4_new=. age_s_new=. _weight0_=0.6826918167 i=. _weight_=. _ERROR_=1 _N_=4
>  NOTE: The SAS System stopped processing this step because of errors.
>  NOTE: There were 5 observations read from the data set WORK.SW.
>  WARNING: The data set WORK._SWITCH may be incomplete.  When this step was stopped there were 3 observations and 13 variables. 
```

**Comment by gravesti** [comment]
Does that make sense for the weight models? Say if `last_period = 10` but `last_followup = 20` we should not cut off the data when we fit the model based on  `last_period`.

**Comment by lisu-stats** [comment]
As discussed, let's just expand the data using the `first_period/last_period` options, but use the original data for estimating weights.
