### ISSUE TITLE
Save data used for weight models

### ISSUE THREAD

**Issue by gravesti** [CAM-Roche/RandomisedTrialsEmulation#64]
Consider saving data or glm model objects for treatment switching and censoring weights.

**Comment by lisu-stats** [comment]
Maybe leave it as an option to save the data for weight models as model objects? In some scenarios such as simulation studies, this will slow down the program running.

**Comment by gravesti** [comment]
@lisu-stats 
I'm working the option to choose how weight models are saved. The user can select one of the options in `initiators()` or `data_preparation()`:

`save_weight_models = c("tidy", "object", "no")`
This would save either, the tidy summaries (= current behaviour), "object" = the glm objects, "no" = don't save anything.

However I'm not sure I like this design.  I'm thinking to just have the option `save_weight_models = TRUE/FALSE` to save the `glm` objects and always include the summaries in the data_preparation() result.

What do you think?

**Comment by lisu-stats** [comment]
@gravesti I think the TRUE/FALSE option design is better. I agree the summaries of the weight model  can be saved together with data_preparation() result

**Comment by gravesti** [comment]
Ok. I'll change this around
@lisu-stats
