### ISSUE TITLE
'where_case' option does not work properly

### ISSUE THREAD

**Issue by lisu-stats** [CAM-Roche/RandomisedTrialsEmulation#67]
`where_case` should work with `where_var`, which specifies variables to subset the data. 

`where_var` works fine in `data_preparation`, which will take baseline values of these variables at trials and save  them in the expanded data.  However, using `where_case` in `data_modelling`  generates error messages. 

```
> PP_result <-data_modelling(prep_PP_data$data,
+                            outcome_cov =  ~ X1 + X2 + X3 + X4 + age_s, model_var = "assigned_treatment",
+                            use_weight = 1, use_censor = 1,
+                            include_followup_time_case = ~ factor(followup_time),
+                            include_expansion_time_case = ~ 1,
+                            glm_function = c("glm"), #,glm_function = c("parglm", "glm")
+                            use_sample_weights = F
+                            ,first_followup =0,
+                            last_followup = 4
+                            ,where_case = 'age>30')
Error in if (numCores == 1) { : missing value where TRUE/FALSE needed
Timing stopped at: 0.002 0 0.002
```

**Comment by gravesti** [comment]
@lisu-stats 
I'm working on this one. It was an easy fix, but it leads me to think about structuring the output better.

Potentially we have a list of models:

* base model
   * weighted
   * p99/limited weights
   * unweighted
* one for each where condition

Currently only one model is returned and the others are printed only.
Also only 1 weighted outcome model is run. Do we want to allow different options eg unweighted and p99?

**Comment by lisu-stats** [comment]
@gravesti Do you mean to return results from multiple models with different weights? Right now, we have options such as `run_unweighted_analysis` etc if users require different weighted models to be fit. I reckon that having multiple models returned doesn't save computing time, right? If this is the case, then I think it may be fine to ask users to call for different models using separate commands. What do you think?

**Comment by lisu-stats** [comment]
@gravesti Unless you want to add this option in the `initiators()`, which makes sense as we don't want to expand data multiple times.

**Comment by lisu-stats** [comment]
@gravesti A different question: I wonder if we can omit to print the Sandwich matrix on the screen. I am trying to add the output to the paper, but the matrix took up too much space. Thanks!

**Comment by gravesti** [comment]
@lisu-stats 
Ok to hide the matrix.

Currently I think it's confusing because a user can specifiy `run_unweighted_analysis=1` and `run_p99_analysis=1` but they only get the results of one of them.

Agree that multiple objects would save time for initiators

**Comment by lisu-stats** [comment]
@gravesti I got your point now. Yes, it is better to merge these options into one and set the default as the weighted analysis without truncation.

**Comment by gravesti** [comment]
@lisu-stats 
So `data_modelling()` will only fit and return one model: the selected weighting option (or unweighted) with all where conditions applied

**Comment by lisu-stats** [comment]
@gravesti Sounds good!

**Comment by lisu-stats** [comment]
@gravesti Thanks. `where_case` works now. A couple of small points about the output printed on the screen:

1) If we set a condition in `where_case`, can we replace the label 'Base analysis' with "Subsetting data with age>=30"? Right now, both are printed. 

2) Can we still print the model summary with the robust standard errors, but not the sandwich matrix? Right now, no model summary with robust SE is printed on the screen.
