### ISSUE TITLE
'treatment' variable in the expanded data

### ISSUE THREAD

**Issue by lisu-stats** [CAM-Roche/RandomisedTrialsEmulation#81]
@gravesti Just found out that the treatment variable returned from `data_preparation ` does not look right. 

These are the original data

```
> print(simdata_censored[simdata_censored$ID<=4,], digits=2)
    ID t A X1    X2 X3    X4 age age_s Y C eligible
 1:  1 0 1  0 -0.35  0  0.96  49  1.17 0 1        1
 2:  2 0 1  1 -1.15  1  1.70  30 -0.42 0 0        1
 3:  2 1 1  1  1.45  1  1.70  31 -0.33 0 0        0
 4:  2 2 1  0  1.27  1  1.70  32 -0.25 0 1        0
 5:  4 0 0  0 -1.01  0 -0.31  53  1.50 0 0        1
 6:  4 1 0  0  0.38  0 -0.31  54  1.58 0 0        1
 7:  4 2 1  1 -0.44  0 -0.31  55  1.67 0 0        1
 8:  4 3 1  1  0.20  0 -0.31  56  1.75 0 0        0
 9:  4 4 1  0 -0.45  0 -0.31  57  1.83 0 0        0
10:  4 5 1  0  0.24  0 -0.31  58  1.92 0 0        0
11:  4 6 1  1  0.20  0 -0.31  59  2.00 0 0        0
12:  4 7 0  0 -0.19  0 -0.31  60  2.08 0 0        0
13:  4 8 1  1 -0.50  0 -0.31  61  2.17 0 0        0
14:  4 9 1  0  0.43  0 -0.31  62  2.25 0 0        0
```

After data expansion for the ITT analysis, the values in the column `treatment` do not match the time-varying values of treatment at the current visit for trial 0.  For example, for trial 0, visit 0, the treatment is 1. This is not correct.  But for later trials, the treatment values look alright. Also, the `dose` variable looks OK to me when called in `data_preparation`

```
> print(prep_ITT_data$data[prep_ITT_data$data$id==4, c("id","for_period","followup_time","outcome","weight" ,"treatment","assigned_treatment")], digits=2)
    id for_period followup_time outcome weight treatment assigned_treatment
 1:  4          0             0       0   1.00         1                  0
 2:  4          0             1       0   0.90         0                  0
 3:  4          0             2       0   0.77         0                  0
 4:  4          0             3       0   0.74         1                  0
 5:  4          0             4       0   0.70         1                  0
 6:  4          0             5       0   0.67         1                  0
 7:  4          0             6       0   0.64         1                  0
 8:  4          0             7       0   0.61         1                  0
 9:  4          0             8       0   0.51         0                  0
10:  4          0             9       0   0.49         1                  0
11:  4          1             0       0   1.00         0                  0
12:  4          1             1       0   0.86         1                  0
13:  4          1             2       0   0.82         1                  0
14:  4          1             3       0   0.78         1                  0
15:  4          1             4       0   0.75         1                  0
16:  4          1             5       0   0.71         1                  0
17:  4          1             6       0   0.67         0                  0
18:  4          1             7       0   0.57         1                  0
19:  4          1             8       0   0.54         1                  0
20:  4          2             0       0   1.00         1                  1
21:  4          2             1       0   0.95         1                  1
22:  4          2             2       0   0.91         1                  1
23:  4          2             3       0   0.87         1                  1
24:  4          2             4       0   0.83         1                  1
25:  4          2             5       0   0.79         0                  1
26:  4          2             6       0   0.67         1                  1
27:  4          2             7       0   0.63         1                  1

```

**Comment by gravesti** [comment]
@lisu-stats Yes, I've noticed something strange in `treatment` before. I think it's because somewhere in the data processing it copies from the row above, possibly from the previous patient.
I don't think this variable is used by default in any other model, but it should be correct.

**Comment by lisu-stats** [comment]
@gravesti We could simply remove this variable if it is too much hassle to find a fix.

**Comment by gravesti** [comment]
@lisu-stats Currently are two pieces of code which define treatment:
 1. defined as the treatment in the previous period. 
 2. `if (use_censor==1) treatment <- assigned_treatment`

I don't think 2. is useful, so this can be removed.

Do you think it is informative to have the lagged treatment? Maybe for as-treated as another option instead of the cumulative "dose". What would the treatment value be in the first time period for each patient? 0?

Should "treatment" instead be the actual treatment received in the period?

**Comment by lisu-stats** [comment]
@gravesti 
agree 2. can be removed as we already have `assigned_treatment` in the data.

For later trials other than trial 0, the` treatment` variable looks alright. So it is only for trial 0, where the lagged values of treatment were used instead of current values. I think for as_treated analyses, it may be useful to keep it since users may want to create their own functions of the treatment sequence and use them in the outcome models. But we need to fix the error in the initial trial.

For the paper, I will not explain the as_treated analyses because there is no formal estimand in such analyses. But we can keep it in the package for anyone interested in exploring.
