### ISSUE TITLE
case_control_sampling_trials function

### ISSUE THREAD

**Issue by lisu-stats** [CAM-Roche/RandomisedTrialsEmulation#83]
@gravesti Can we add an option to specify a seed for the sampling? I want to make sure the results in the paper can be reproduced with the R script

Also, we can remove the option `n_control` as discussed

**Comment by gravesti** [comment]
@lisu-stats I've substantially reworked the sampling code and added unit tests.
The code now supports sampling when `data_preparation(separate_files = TRUE)` and also `FALSE`.

I don't think adding an additional seed argument is necessary. It should enough to write
```r

 dat <- trial_example[trial_example$id < 200, ]
  expanded_data <- data_preparation(
    data = dat,
    outcome_cov = c("nvarA", "nvarB", "nvarC"),
    first_period = 260,
    last_period = 280,
    separate_files = FALSE,
    quiet = TRUE
)
set.seed(12345)
samples <- case_control_sampling_trials(expanded_data, p_control = 0.01, sample_all_time = FALSE)
```
I have added an option `sort = TRUE` , which is necessary to get the same results for separate_trial TRUE/FALSE.

We have a `subset_condition` argument in this function, which can sub the data before sampling, and therefore the affects sample weights. I suppose this will cause the final model to have different weights depending where we do the subsetting. It seems like subsetting here would be more correct, as the denominator the number of controls in the group of interest.

**Comment by lisu-stats** [comment]
@gravesti Thanks a lot, Isaac. I've tried the new version, it worked well. 

I wonder if we should set `sample_all_time = TRUE` as the default. This is because we need to sample controls at all visits if we want to predict cumulative incidences. When `sample_all_time = FALSE`, the baseline hazards will not be consistently estimated. I will emphasize this in the paper.
